Repository JuliaPlots/UnicodePlots.jl, pull requests merged in 2022-11, with the labels that each got.

#301 update contour colormap `zlim` - disable labels on `3d` plots
  src/UnicodePlots.jl
  src/interface/barplot.jl
  src/interface/boxplot.jl
  src/interface/contourplot.jl
  src/interface/histogram.jl
  src/interface/isosurface.jl
  src/interface/spy.jl
  src/interface/surfaceplot.jl
  test/references_24/contourplot/consistency.txt
  test/references_24/contourplot/function_contour.txt
  test/references_24/contourplot/gauss_5levels.txt
  test/references_24/contourplot/gauss_cividis.txt
  test/references_24/contourplot/gauss_nested.txt
  test/references_24/isosurface/hyperboloid.txt
  test/references_24/isosurface/sphere.txt
  test/references_24/isosurface/torus.txt
  test/references_24/surfaceplot/consistency.txt
  test/references_24/surfaceplot/interpolation.txt
  test/references_24/surfaceplot/matrix.txt
  test/references_24/surfaceplot/mutate.txt
  test/references_24/surfaceplot/single_color.txt
  test/references_24/surfaceplot/slice_lines.txt
  test/references_24/surfaceplot/slice_scatter.txt
  test/references_24/surfaceplot/sombrero.txt
  test/references_24/surfaceplot/sombrero_aspect.txt
  test/references_24/surfaceplot/sombrero_zscale.txt
  test/references_8/contourplot/consistency.txt
  test/references_8/contourplot/function_contour.txt
  test/references_8/contourplot/gauss_5levels.txt
  test/references_8/contourplot/gauss_cividis.txt
  test/references_8/contourplot/gauss_nested.txt
  test/references_8/isosurface/hyperboloid.txt
  test/references_8/isosurface/sphere.txt
  test/references_8/isosurface/torus.txt
  test/references_8/surfaceplot/consistency.txt
  test/references_8/surfaceplot/interpolation.txt
  test/references_8/surfaceplot/matrix.txt
  test/references_8/surfaceplot/mutate.txt
  test/references_8/surfaceplot/single_color.txt
  test/references_8/surfaceplot/slice_lines.txt
  test/references_8/surfaceplot/slice_scatter.txt
  test/references_8/surfaceplot/sombrero.txt
  test/references_8/surfaceplot/sombrero_aspect.txt
  test/references_8/surfaceplot/sombrero_zscale.txt
  test/tst_contourplot.jl
  test/tst_surfaceplot.jl
Labels: bug, enhancement

#302 simplifications - swap transform order
  src/common.jl
  src/interface/isosurface.jl
  src/interface/surfaceplot.jl
  src/plot.jl
  src/volume.jl
Labels: documentation, style

#303 change `surfaceplot` default aspect
  README.md
  docs/gen_docs.jl
  src/description.jl
  src/interface/surfaceplot.jl
  src/show.jl
  test/references_24/surfaceplot/consistency.txt
  test/references_24/surfaceplot/interpolation.txt
  test/references_24/surfaceplot/matrix.txt
  test/references_24/surfaceplot/mutate.txt
  test/references_24/surfaceplot/single_color.txt
  test/references_24/surfaceplot/sombrero.txt
  test/references_24/surfaceplot/sombrero_aspect.txt
  test/references_24/surfaceplot/sombrero_identity.txt
  test/references_24/surfaceplot/sombrero_zscale.txt
  test/references_8/surfaceplot/consistency.txt
  test/references_8/surfaceplot/interpolation.txt
  test/references_8/surfaceplot/matrix.txt
  test/references_8/surfaceplot/mutate.txt
  test/references_8/surfaceplot/single_color.txt
  test/references_8/surfaceplot/sombrero.txt
  test/references_8/surfaceplot/sombrero_aspect.txt
  test/references_8/surfaceplot/sombrero_identity.txt
  test/references_8/surfaceplot/sombrero_zscale.txt
  test/tst_io.jl
  test/tst_surfaceplot.jl
Labels: bug

#305 add `Term` examples
  README.md
  docs/gen_docs.jl
Labels: documentation

#306 add links
  README.md
  docs/gen_docs.jl
Labels: documentation

#309 add mutability tests
  src/freetype.jl
  src/show.jl
  test/tst_freetype.jl
  test/tst_plot.jl
Labels: ci

#310 README: Fix two section headings
  README.md
  docs/gen_docs.jl
Labels: documentation

#312 `unicode_exponent` consistency
  src/common.jl
  src/interface/boxplot.jl
  src/plot.jl
  src/show.jl
  test/references_24/contourplot/function_contour.txt
  test/references_24/contourplot/gauss_nested.txt
  test/references_24/scatterplot/scale3.txt
  test/references_8/contourplot/function_contour.txt
  test/references_8/contourplot/gauss_nested.txt
  test/references_8/scatterplot/scale3.txt
  test/tst_common.jl
Labels: bug, enhancement

#314 fix `surfaceplot` masking using `NaN`s
  src/canvas.jl
  src/common.jl
  test/references_24/surfaceplot/masked_values_lines.txt
  test/references_24/surfaceplot/masked_values_points.txt
  test/references_8/surfaceplot/masked_values_lines.txt
  test/references_8/surfaceplot/masked_values_points.txt
  test/tst_surfaceplot.jl
Labels: bug

#316 simplify test
  test/tst_surfaceplot.jl
Labels: ci
