Repository JuliaPlots/UnicodePlots.jl, pull requests merged in 2024-04, with the labels that each got.

#377 update ci yml (codecov)
  .github/workflows/ci.yml
  .github/workflows/format-check.yml
  .github/workflows/invalidations.yml
Labels: ci

#379 Fix downloads count badge
  README.md
Labels: enhancement, documentation

#380 fix badge
  README.md
  docs/gen_docs.jl
Labels: documentation
