Repository JuliaPlots/UnicodePlots.jl, pull requests merged in 2025-07, with the labels that each got.

#412 update docs
  docs/make.jl
  docs/src/index.md
Labels: documentation

#413 enrich dows
  docs/Project.toml
  docs/src/api.md
  docs/src/dev.md
  docs/src/manual.md
Labels: documentation

#414 update docs
  docs/make.jl
  docs/src/api.md
  docs/src/dev.md
  docs/src/index.md
  docs/src/interface.md
  docs/src/notes.md
Labels: documentation

#419 add `pre-commit` hook
  .pre-commit-config.yaml
Labels: quality

#420 implement `OctantCanvas`
  docs/src/dev.md
  docs/src/index.md
  src/UnicodePlots.jl
  src/canvas/octantcanvas.jl
  test/runtests.jl
  test/tst_scatterplot.jl
Labels: enhancement
